#
#███████╗ █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#╚══███╔╝██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███╔╝ ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ███╔╝  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#███████╗██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝


import = ["/home/zasbirrahman/.config/alacritty/colors.toml", "/home/zasbirrahman/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
opacity = 0.7

[window.dimensions]
columns = 115
lines = 20

[window.padding]
x = 20
y = 20

#[font]
#normal.family = "MorePerfectDOSVGA"
#bold.family =  "MorePerfectDOSVGA"
#italic.family = "MorePerfectDOSVGA"
#bold_italic.family = "MorePerfectDOSVGA"

#[font]
#normal.family =  "JetBrains Mono NL"
#bold.family = "JetBrains Mono NL"
#italic.family = "JetBrains Mono NL"
#bold_italic.family = "JetBrains Mono NL"

[font]
normal.family = "LessPerfectDOSVGA"
bold.family =  "LessPerfectDOSVGA"
italic.family = "LessPerfectDOSVGA"
bold_italic.family = "LessPerfectDOSVGA"


#normal.family = "CartographCF"
#bold.family =  "CartographCF"
#italic.family = "CartographCF"
#bold_italic.family = "CartographCF"


#normal.family = "tamzen"
#bold.family =  "tamzen"
#italic.family = "tamzen"
#bold_italic.family = "tamzen"



