


# ________  ________  _________  ___  ___
#|\   ____\|\   __  \|\___   ___\\  \|\  \
#\ \  \___|\ \  \|\  \|___ \  \_\ \  \\\  \
# \ \  \  __\ \  \\\  \   \ \  \ \ \   __  \
#  \ \  \|\  \ \  \\\  \   \ \  \ \ \  \ \  \
#   \ \_______\ \_______\   \ \__\ \ \__\ \__\
#    \|_______|\|_______|    \|__|  \|__|\|__|
#               theme stolen from some dude's dotfiles. 



#[colors.bright]
#black = "0x475258"
#blue = "0x7fbbb3"
#cyan = "0x83c092"
#green = "0xa7c080"
#magenta = "0xd699b6"
#red = "0xe67e80"
#white = "0xd3c6aa"
#yellow = "0xdbbc7f"

#[colors.normal]
#black = "0x1e2326"
#blue = "0x7fbbb3"
#cyan = "0x83c092"
#green = "0xa7c080"
#magenta = "0xd699b6"
#red = "0xe67e80"
#white = "0xd3c6aa"
#yellow = "0xdbbc7f"

#[colors.primary]
#background = "0x1e2326"
#foreground = "0xd3c6aa"





# _________  ________  ___  __        ___    ___ ________
#|\___   ___\\   __  \|\  \|\  \     |\  \  /  /|\   __  \
#\|___ \  \_\ \  \|\  \ \  \/  /|_   \ \  \/  / | \  \|\  \
#     \ \  \ \ \  \\\  \ \   ___  \   \ \    / / \ \  \\\  \
#      \ \  \ \ \  \\\  \ \  \\ \  \   \/  /  /   \ \  \\\  \
#       \ \__\ \ \_______\ \__\\ \__\__/  / /      \ \_______\
#        \|__|  \|_______|\|__| \|__|\___/ /        \|_______|
#                                   \|___|/
#           theme stolen from some dotfiles on github.





# Default colors
#[colors.primary]
#background = "#1a1b26"
#foreground = "#a9b1d6"

# Cursor colors
#[colors.cursor]
#cursor = "#bb9af7"
#text = "#1a1b26"

# Normal colors
#[colors.normal]
#black = "#32344a"
#blue = "#7aa2f7"
#cyan = "#449dab"
#green = "#9ece6a"
#magenta = "#ad8ee6"
#red = "#f7768e"
#white = "#787c99"
#yellow = "#e0af68"

# Bright colors
#[colors.bright]
#black = "#444b6a"
#blue = "#7da6ff"
#cyan = "#0db9d7"
#green = "#b9f27c"
#magenta = "#bb9af7"
#red = "#ff7a93"
#white = "#acb0d0"
#yellow = "#ff9e64"


# ________  ________      ___    ___ ________  ________
#|\_____  \|\   __  \    |\  \  /  /|\   __  \|\   ___  \
# \|___/  /\ \  \|\  \   \ \  \/  / | \  \|\  \ \  \\ \  \ ' 
#     /  / /\ \   __  \   \ \    / / \ \   __  \ \  \\ \  \  S
#    /  /_/__\ \  \ \  \   \/  /  /   \ \  \ \  \ \  \\ \  \
#   |\________\ \__\ \__\__/  / /      \ \__\ \__\ \__\\ \__\
#    \|_______|\|__|\|__|\___/ /        \|__|\|__|\|__| \|__|
#                       \|___|/                                 THEME
# (which is also kind of stolen from some other dude's config)

#[colors.primary]
#background = "#11111C"
#foreground = "#e0def4"


#[colors.normal]
#black = "#181b28"
#blue = "#7aa2f7"
#cyan = "#449dab"
#green = "#9ece6a"
#magenta = "#ad8ee6"
#red = "#f7768e"
#white = "#787c99"
#yellow = "#e0af68"

#[colors.bright]
#black = "#181b28"
#blue = "#7da6ff"
#cyan = "#0db9d7"
#green = "#b9f27c"
#magenta = "#bb9af7"
#red = "#ff7a93"
#white = "#acb0d0"
#yellow = "#ff9e64"


#███████╗██████╗  █████╗  ██████╗███████╗
#██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝
#███████╗██████╔╝███████║██║     █████╗
#╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝
#███████║██║     ██║  ██║╚██████╗███████╗
#╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝
#   a wal theme


#[colors.primary]
#background='#0c0e12'
#foreground='#a6c6ca'
#
#[colors.normal]
##black='#0c0e12'
##blue='#a6c6ca'
##magenta='#9b709f'
##red='#c66a5d'
##white='#e0def1'
#yellow='#ba9371'


# █╗    ██╗ █████╗ ██╗
#██║    ██║██╔══██╗██║
#██║ █╗ ██║███████║██║
#██║███╗██║██╔══██║██║
#╚███╔███╔╝██║  ██║███████╗
# ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝ it's really gruvbox

#[colors.primary]
#background='#282828'
#foreground='#ebdbb2'
#
#[colors.normal]
#black='#1d2021'
#red='#cc241d'
#green='#98971a'
#yellow='#d79921'
#blue='#458588'
#magenta='#b16286'
#cyan='#689d6a'
#
#
#[colors.bright]
#black='#3c3836'
#red='#fb4934'
#green='#b8bb26'
#yellow='#fabd2f'
#blue='#83a598'
#magenta='#d3869b'
#cyan='#8ec07c'


# ██████╗ ██████╗ ██╗   ██╗██╗   ██╗██████╗  ██████╗ ██╗  ██╗
#██╔════╝ ██╔══██╗██║   ██║██║   ██║██╔══██╗██╔═══██╗╚██╗██╔╝
#██║  ███╗██████╔╝██║   ██║██║   ██║██████╔╝██║   ██║ ╚███╔╝
#██║   ██║██╔══██╗██║   ██║╚██╗ ██╔╝██╔══██╗██║   ██║ ██╔██╗
#╚██████╔╝██║  ██║╚██████╔╝ ╚████╔╝ ██████╔╝╚██████╔╝██╔╝ ██╗
# ╚═════╝ ╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚═════╝  ╚═════╝ ╚═╝  ╚═╝

[colors.primary]
background='#1d2021'
foreground='#d5c4a1'

[colors.normal]
black='#1d2021'
red='#fb4934'
green='#b8bb26'
yellow='#fabd2f'
blue='#83a598'
magenta='#d3869b'
cyan='#8ec07c'
white='#fbf1c7'
