#! /bin/sh
#
#███████╗███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#╚══███╔╝██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ███╔╝ ███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
# ███╔╝  ╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#███████╗███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚══════╝╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝









## MADE BY ZASBIR RAHMAN ZAYAN 


### AUTOSTART

polybar &
alacritty &
feh --bg-scale ~/Downloads/weirdbackground.png
killall nm-applet && nm-applet &
pgrep -x sxhkd > /dev/null || sxhkd &



### GLOBAL SETTINGS

bspc config focus_follows_pointer 	true
bspc config pointer_follows_pointer 	false
bspc config click_to_focus 		false
xsetroot -cursor_name           left_ptr

### BSPWM COLORING

bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config active_border_color 	"#1e1e1e"
bspc config presel_feedback_color 	"#5e81ac"	
bspc config pointer_modifier		 shift


### MONITOR AND DESKTOP SETTINGS

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config top_padding 	32
bspc config right_padding 	0
bspc config bottom_padding 	0
bspc config left_padding 	0
bspc config window_gap 		10



## NODE SETTINGS

bspc config border_width 2 

## WINDOW RULES

#BLANK FOR NOW

