#! /bin/sh
#
#███████╗███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#╚══███╔╝██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ███╔╝ ███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
# ███╔╝  ╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#███████╗███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚══════╝╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝


### SOURCE THE COLOR


#. "${HOME}/Downloads/gitthings/dotfiles/wal/colors.sh"
. "${HOME}/.cache/wal/colors.sh"



## MADE BY ZASBIR RAHMAN ZAYAN


### AUTOSTART

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Downloads/gitthings/dotfiles/wallpapers/gruvboxwallpaper.png
polybar &
alacritty &



### GLOBAL SETTINGS

	# POINTER SETTINGS
bspc config focus_follows_pointer 		  true
bspc config pointer_follows_focus 		  false
bspc config pointer_follows_monitor		  false
bspc config click_to_focus 		          false
bspc config pointer_modifier			  shift

	# MONOCLE SETTINGS

bspc config borderless_monocle			  false
bspc config gapless_monocle			  false
bspc config single_monocle 			  false

	# INTERRUPT SETTINGS

bspc config ignore_ewmh_focus 			  true
bspc config ignore_emwh_fullscreen		  true
bspc config ignore_emwh_struts		          false

	# INSERTION SCHEME 

bspc config automatic_scheme 			  spiral

	# PRESEL FEEDBACK

bspc config presel_feedback 			  true

	# MONITOR

bspc config remove_disabled_monitors		  true
bspc config remove_unplugged_monitors		  true


### BSPWM COLORING (also global)

bspc config normal_border_color		    "$color1"
bspc config focused_border_color	    "$color15"
bspc config active_border_color 	    "$color2"
bspc config presel_feedback_color 	  "$color1"


### MONITOR AND DESKTOP SETTINGS

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config top_padding 	        32
bspc config right_padding      	        0
bspc config bottom_padding     	        0
bspc config left_padding 	        0
bspc config window_gap 		        10



## NODE SETTINGS

bspc config border_width   		 2

## WINDOW RULES

bspc rule -a Lxappearance state=floating
bspc rule -a Vlc state=fullscreen

