--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zasbirrahman/Downloads/jellyfishinspace.jpeg"

-- Special
background="#0c0e12"
foreground="#a6c6ca"
cursor="#a6c6ca"

-- Colors
color0="#0c0e12"
color1="#58565E"
color2="#996459"
color3="#C66A5D"
color4="#BA9371"
color5="#6E7186"
color6="#9B709F"
color7="#a6c6ca"
color8="#748a8d"
color9="#58565E"
color10="#996459"
color11="#C66A5D"
color12="#BA9371"
color13="#6E7186"
color14="#9B709F"
color15="#a6c6ca"
