# Shell variables
# Generated by 'wal'
wallpaper="/home/zasbirrahman/Downloads/jellyfishinspace.jpeg"

# Special
background='#0c0e12'
foreground='#a6c6ca'
cursor='#a6c6ca'

# Colors
color0='#0c0e12'
color1='#58565E'
color2='#996459'
color3='#C66A5D'
color4='#BA9371'
color5='#6E7186'
color6='#9B709F'
color7='#a6c6ca'
color8='#748a8d'
color9='#58565E'
color10='#996459'
color11='#C66A5D'
color12='#BA9371'
color13='#6E7186'
color14='#9B709F'
color15='#a6c6ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
